#!/bin/bash

chown www-data:www-data /var/www -R

rm -rf /var/www/html

while ! (mysqladmin ping --host=database --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1)
do
   sleep 3
   echo "Waiting till MySQL service is available..."
done

cd /var/www || exit 1

if [ ! -f "/var/www/wp-config.php" ]; then
  su www-data -c "wp core download"
fi

if [ -f "/var/www/wp-config.php" ]; then
  echo "Backing up wp-config.php file..."
  mv "/var/www/wp-config.php" "/var/www/wp-config.php.bak"
fi

RES=$(su www-data -c "wp core config --dbname=$MYSQL_DATABASE --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=database")
if [[ $RES != *"Success"* ]]; then
  echo "Failed to create config..."
  if [ -f "/var/www/wp-config.php.bak" ]; then
    echo "Restoring wp-config.php backup..."
    mv "/var/www/wp-config.php.bak" "/var/www/wp-config.php"
  fi
  exit 1
fi

if [ -f "/var/www/wp-config.php.bak" ]; then
  echo -n "Removing wp-config.php backup..."
  rm -f "/var/www/wp-config.php.bak"
fi

RES=$(su www-data -c "wp  db query 'SHOW DATABASES LIKE \"$MYSQL_DATABASE_SINGLE\";'" )
if [[ ! ${#RES} -gt 0 ]]; then
  echo "Database not found, creating database..."
  su www-data -c "wp  db create"
  exit 1
fi

rm -f "/var/www/wp-config.php"
echo "Creating config..."
su www-data -c "wp  core config --dbname=$MYSQL_DATABASE --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=database <<PHP
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', '/proc/self/fd/2');
define('WP_DEBUG_DISPLAY', true);
define('WP_MEMORY_LIMIT', '512M');
PHP"


chmod 644 "/var/www/wp-config.php"

echo "Installing WP"
su www-data -c "wp  core install --url=\"${WP_SITE_URL}\" --title=\"Triple Bits - WordPress\" --admin_user=\"${WP_ADMIN_USERNAME}\" --admin_password=\"${WP_ADMIN_PASSWORD}\" --admin_email=\"${WP_ADMIN_EMAIL}\""

echo "Disabling Unnecessary Plugins"
su www-data -c "wp plugin deactivate hello"
su www-data -c "wp plugin deactivate akismet"
su www-data -c "wp plugin delete hello"
su www-data -c "wp plugin delete akismet"

UPLOADS_PATH="/var/www/wp-content/uploads"
if [ ! -d $UPLOADS_PATH ]; then
  echo "Enabling uploads..."
  mkdir $UPLOADS_PATH
  chmod 775 $UPLOADS_PATH
fi

cd /var/www || exit 1
