version: '3.7'

volumes:
  database:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

services:
  database:
    image: mariadb:10.4
    command:
      --max_allowed_packet=1073741824
      --innodb_log_file_size=1073741824
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DOCKER_GATEWAY_IP}:3306:3306
  php-fpm:
    image: triplebits/php:7.4-fpm
    build: ./docker/php/7.4-fpm
    env_file: .env
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./var/www:/var/www
      - ./src/.:/var/www/wp-content/plugins/triplebits-wp-plugin-sample
      - ./docker/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/install/install:/usr/local/bin/install:ro
  nginx:
    image: triplebits/nginx:latest
    tty: true
    depends_on:
      - database
      - php-fpm
    volumes:
      - ./var/www:/var/www
      - ./docker/nginx/sites-enabled/.:/etc/nginx/sites-enabled
    ports:
      - ${DOCKER_GATEWAY_IP}:80:80
      - ${DOCKER_GATEWAY_IP}:443:443